# faceSpec: eightmovies
# faceSpec: twocats
# faceSpec: onemovie
# faceSpec: vikingplaza
# faceSpec: eightpics
faceSpec: wolf

doWolf: true
wolfFrames: 1
doInitRotate: true
doCube: true
doCarrousel: false
doStars: false
doTorus: false
doBackground: false
doTransformTest: false
