# faceSpec: eightmovies
# faceSpec: twocats
faceSpec: extreme

doWolf: false
wolfFrames: all
doInitRotate: false
doCube: true
doCarrousel: false
doStars: false
doTorus: false
doBackground: false
doTransformTest: false
