# faceSpec: eightmovies
# faceSpec: twocats
# faceSpec: onemovie
# faceSpec: vikingplaza
faceSpec: eightpics

doWolf: true
wolfFrames: all
doInitRotate: true
doCube: true
doCarrousel: false
doStars: false
doTorus: false
doBackground: false
doTransformTest: false
