# faceSpec: eightmovies
# faceSpec: twocats
# faceSpec: onemovie
# faceSpec: vikingplaza
# faceSpec: eightpics
# faceSpec: wolf
faceSpec: wolf

doWolf: false
wolfFrames: all
doInitRotate: true
doCube: false
doCarrousel: false
doStars: false
doTorus: false
doBackground: false
doTransformTest: false
