name:                sdl-cairo-gl-photo-cube
version:             0.1.0.0
github:              "githubuser/sdl-cairo-gl-photo-cube"
license:             BSD3
author:              "Allen Haim"
maintainer:          "allen@netherrealm.net"
copyright:           "2018 Allen Haim"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/githubuser/sdl-cairo-gl-photo-cube#readme>

dependencies:
- base >= 4.7 && < 5
- OpenGL >= 3.0.2.0 && < 3.0.3
- svg-tree >= 0.6.2.1 && < 0.6.3
- sdl2 >= 2.3.0 && < 2.4
- linear >= 1.20.7 && < 1.21
- cairo >= 0.13.4.1 && < 0.13.5
- filepath >= 1.4.1.1
- array >= 0.5.1.1
- bytestring >= 0.10.8.1
- JuicyPixels >= 3.2.8.3
- vector >= 0.11.0.0
- base64-bytestring >= 1.0.0.1
- StateVar >= 1.1.0.4 && < 1.1.1
- sdltricks-cat >= 0.1.0.4
- time

library:
  source-dirs: src
  ghc-options:
  - -XPatternSynonyms
  extensions:
  - PatternSynonyms

#executables:
#  sdl-cairo-gl-photo-cube-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    - -XPatternSynonyms
#    extensions:
#    - PatternSynonyms
#    dependencies:
#    - sdl-cairo-gl-photo-cube
